# Unique key
sonar.projectKey=rdroge_genericservice
sonar.organization=rdroge
# Display name in SonarQube
sonar.projectName=GenericService
sonar.projectVersion=1.0
sonar.projectDescription=GenericService API 

# Comma-separated list of directories - Dump contains .df files, and src/openedge contains source code
sonar.sources=src
# Comma-separated list of patterns to be excluded
sonar.exclusions=
sonar.sourceEncoding=iso8859-1
# Directory where r-code can be found
sonar.oe.binaries=output/build-output
# Comma-separated list of PL or directories
sonar.oe.propath=src
# OpenEdge installation path (see next property)
sonar.oe.dlc=/usr/dlc
# Append $DLC/gui, $DLC/tty and $DLC/src to the propath
sonar.oe.propath.dlc=true
# Comma-separated list of full DF files
# sonar.oe.databases=dump/sp2k.df
# Semi colon separated list of entries, each entry is a comma-separated list of aliases (first entry is the db name)
# sonar.oe.aliases=sp2k,db1,db2
# No Copy-Paste Detection on DF files
# sonar.cpd.exclusions=dump/**
# Set to true to generate token listing in .tokens subdirectory
sonar.oe.cpd.debug=false
# Set to true to generate AST for each file in .proparse subdirectory
sonar.oe.proparse.debug=false
# Default extensions are .p, .w, .i and .cls. Use this option if you have additional extensions to analyze
# sonar.oe.file.suffixes=p,w,t
# Comma-separated list of directories where *.out files will be parsed for code coverage
# sonar.oe.coverage.profiler.dirs=target/profiler
# Analytics data (number of OE files analyzed + timings) sent by default to Riverside Software. Set property to false to disable data collection
sonar.oe.analytics=true