version: '3.8'

services:

  devcontainer:
    image: ${DEVCONTAINER_IMAGE}
    privileged: true
    volumes:
      - ../..:/workspaces:cached
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
      - ./windsurf/.windsurf:/home/openedge/.windsurf
      - ./windsurf/.codeium:/home/openedge/.codeium
    ports:
      - ${DEBUG_PORT}:3099
    command: sleep infinity

  sports2020-db:
    image: ${DB_IMAGE}
    user: openedge
    volumes:
    #  - ../src/schema/sports2020.df:/app/schema/sports2020.df
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
    ports:
      - 10000-10010:10000-10010
    environment:
      - DBNAME=sports2020    
      
  sports2020-pas:
    image: ${PAS_IMAGE}
    user: openedge
    volumes:
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
      - ../src:/app/src
      - ../conf/as.pf:/app/config/as.pf
      - ../conf/openedge.properties:/app/pas/as/conf/openedge.properties
      - ../conf/otelconfig.json:/app/pas/as/openedge/otelconfig.json
      - ./logs:/app/pas/as/logs

    ports:
      - ${PAS_PORT}:8810
      - ${PAS_HTTPS_PORT}:8811
    environment:
      - PASWEBHANDLERS=/app/src/webhandlers/ROOT.handlers
    depends_on:
      - sports2020-db

  # jaeger:
  #  image: jaegertracing/all-in-one:1.35
  #  container_name: jaeger
  #  environment:
  #    - COLLECTOR_OTLP_ENABLED=true
  #  ports:
  #    - "4317-4318:4317-4318"
  #    - "16685-16686:16685-16686"
    